### DISCUSSION TITLE
Unable to get project name or filepath

### DISCUSSION THREAD

**Discussion by eureka-cpu** [helgoboss/reaper-rs#84] [Q&A] [answered]
Ref #82 

I'm having trouble getting the project info I need, and previously I was using the crates.io version and didn't realize I needed to use master, so I ended up writing the plugin using the ReaPy from PyPy to write the plugin logic. I'm able to get this output and the python plugin works fine, but I'd really like to use reaper-rs to do this. Here is a json blob created by the python plugin:
```json
{
  "name": "test_proj.RPP",
  "media_path": "/home/eureka/Documents/REAPER Media/test_proj/Media",
  "rpp_filepath": "/home/eureka/Documents/REAPER Media/test_proj/test_proj.RPP",
  "tracks": [
    {
      "name": "Empty_Track",
      "project_name": "test_proj.RPP",
      "project_media_path": "/home/eureka/Documents/REAPER Media/test_proj/Media",
      "project_rpp_filepath": "/home/eureka/Documents/REAPER Media/test_proj/test_proj.RPP",
      "media_items": []
    }
  ],
  "modtime": "2025-04-03T05:24:10.555949+00:00",
  "author": "eureka",
  "host": "tensorbook",
  "trigger": "OnStart"
}
```

**Comment by eureka-cpu** [comment]
Here is my rust plugin and my toml contents:
```rust
use reaper_high::Reaper;
use reaper_macros::reaper_extension_plugin;

#[reaper_extension_plugin(
    name = "reaper_lib_cloud_reaper",
    support_email_address = "cloudscythelabs@gmail.com",
    update_url = "github.com/Cloud-Scythe-Labs"
)]
pub fn plugin_main() -> Result<(), Box<dyn std::error::Error>> {
    let reaper = Reaper::get();
    reaper.show_console_msg("reaper_lib_cloud_reaper was initialized");
    let project = reaper.current_project();
    if let Some(file_path) = project.file() {
        reaper.show_console_msg(format!("Found file path: '{file_path}'"));
    } else {
        reaper.show_console_msg("did not find the file path");
    }

    Ok(())
}
```
```toml
[package]
name = "reaper_lib_cloud_reaper"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["debug_console"]
# Enables debug messages to be printed to the REAPER console.
debug_console = []

# Important:
#
# Compiled REAPER extension plug-ins (i.e. .dll files) must be prefixed with reaper_ in order
# for REAPER to load them during startup - even on Linux and macOS, where library file names
# usually start with lib. On Windows, it's enough to name the library reaper_my_extension
# in Cargo.toml and it will result in the compiled file being named reaper_my_extension, thus
# obeying this rule. On Linux and macOS, you still need to remove the lib prefix. In any case,
# make sure that the compiled file placed in REAPER_RESOURCE_PATH/UserPlugins is prefixed with
# reaper_ before attempting to test it!

[lib]
name = "_cloud_reaper"  # A post-build fix-up phase will handle the above.
crate-type = ["cdylib"]

[dependencies]
c_str_macro = "1.0"
reaper-high = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
reaper-low.workspace = true # also on master just in the workspace
reaper-macros = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
reaper-medium = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
```
